api:
  required: True
  type: dict
  schema:  
    norway_barents_watch:
      required: True
      type: dict
      schema:
        active:
          required: True
          type: boolean
        T:
          required: True
          type: float